version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      - JVM_OPTS: -Xmx3200m
      - ANDROID_NDK_VERSION: "android-ndk-r16b"
    steps:
      - checkout
      - run: echo ${ANDROID_NDK_VERSION} > _android_ndk_version
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "app/jvm_build.gradle.kts" }}
      - restore_cache:
          key: android_ndk_{{ checksum "_android_ndk_version" }}
      - run:
          name: Install Android NDK
          command: sudo chmod +x ./.circleci/install_ndk.sh && ./.circleci/install_ndk.sh ${ANDROID_NDK_VERSION}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - /opt/android/sdk/ndk
          key: android_ndk_{{checksum "_android_ndk_version"}}
      - run:
          name: Run JVM Tests
          command: ./gradlew -b app/jvm_build.gradle.kts test
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "app/jvm_build.gradle.kts" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
